### ISSUE TITLE
Remove lowercase filter and www filter on URLs

### ISSUE THREAD

**Issue by konklone** [digital-analytics-program/gov-wide-code#10]
The DAP currently includes a filter that lower-cases all URIs:

![screenshot from 2015-03-08 22 59 32](https://cloud.githubusercontent.com/assets/4592/6549290/dc216cc6-c5e6-11e4-90dc-c607451f0c6f.png)

And a filter that removes the `www` from domains:

![screenshot from 2015-03-08 23 04 28](https://cloud.githubusercontent.com/assets/4592/6549319/846c518e-c5e7-11e4-948f-36f7a06838e1.png)

I had previously assumed these were issues intrinsic to Google Analytics, and not specific to the DAP, which is why I am only raising this issue now.

These filters cause issues with the WH Petition site like #9 and https://github.com/GSA/analytics.usa.gov/issues/138, caused some of the hardcoded exceptions in https://github.com/GSA/analytics.usa.gov/pull/129, and are the cause of the nasa.gov problem in https://github.com/GSA/analytics.usa.gov/issues/140.

I understand that the lowercase filter is there to unify websites which use inconsistent case to refer to case-insensitive URLs. However, [URLs are allowed to be case-sensitive](http://www.w3.org/TR/WD-html40-970708/htmlweb.html#h-4.1) (even if [domain names are not](http://tools.ietf.org/html/rfc4343)), and this is causing broken links to appear.

Similarly, though I would greatly prefer that domains handle a missing `www` gracefully, neither the internet not the government requires them to do so at this time.

If there are specific problem domains whose reporting is significantly improved by these filters, let's make the filters only apply to those whitelisted domains, and not to every URL that comes into the DAP.

**Comment by cew821** [comment]
Thanks for tracking this down. @tdlowden -- any thoughts on the above? It does seem like this option could be helpful in some cases, but in other cases it seems like it is a bug in DAP (basically for anyone who is not using case-insensitive URLs, which we have already observed seems to be 1-2 sites in the top 20 at any given time). It seems tough to punish sites that use case-sensitive URLs since URLs are allowed to be case sensitive.

I don't suppose there's a way to change that feature just from what is returned in the "Realtime" api?

**Comment by tdlowden** [comment]
agree, great work Eric. I wasn't aware of this, bc the vendor sets up the filters. 

We could change the filters on the Z3 profile, but it will affect the entire lot of data.

**Comment by konklone** [comment]
> We could change the filters on the Z3 profile, but it will affect the entire lot of data.

Yeah, it's a big change, but I think it will make the data more accurate -- and certainly make the dashboard function more smoothly. I'm a :+1: for making the change.

**Comment by cew821** [comment]
If we were to make this change in DAP settings, would that immediately fix the real time top 20 broken links that are broken because of this issue?

If so, should we do this before launch, or are there reasons we need to keep the setting the change?

**Comment by konklone** [comment]
@cew821 Tim would know better, but I _think_ it would immediately fix the real-time links, and the 7/30-day links that got caught in the crossfire (any who were had their `www` chopped off, or their letters lower-cases) would get split and lose their place in the list -- gradually regaining it over 7 or 30 days.

**Comment by tdlowden** [comment]
@smarina04 what are your thoughts?

**Comment by smarina04** [comment]
Forced lowercase filter was applied on purpose, otherwise, mixed case in URLs is all over the map and it treats the same URL but with different cases as different URLs. When everything is forced to lowercase and makes URLs consistent, then the same URLs but with mixed cases get forced to be unified. We got a lot of those cases in the beginning of DAP and had to apply the lowercase filter to address it.

Removing www was also done on purpose for uniformity reasons.. otherwise, we got WWW, www, or simply a domain w/out "www" and all three would be treated as unique URLs. 

Appending the domain name (otherwise, in GA, everything would appear as part of a page without the domain name vs. full URL) We knew that by appending (faking it basically) the domain name to the pages would cause the links to not work when clicking on them. However, the appearance of full URLs was much more important because we handle thousands of websites vs. one, and agencies would have to guess what domain each page belonged to. So we decided that appending the domain names and thus, breaking the direct links was much more important than being able to click on the links. 

All these and other data standardization techniques were performed because of the messy data we were getting in (remember, it's thousands of websites), which made analysis that much more complicated; e.g. having to merge/sum some of the data, or in cases or metrics (e.g. visits/sessions) the data could not be summed up at all.

**Comment by konklone** [comment]
> When everything is forced to lowercase and makes URLs consistent, then the same URLs but with mixed cases get forced to be unified. We got a lot of those cases in the beginning of DAP and had to apply the lowercase filter to address it.
> 
> Removing www was also done on purpose for uniformity reasons.. otherwise, we got WWW, www, or simply a domain w/out "www" and all three would be treated as unique URLs.

@smarina04 That makes tons of sense. 

I'd love to be able to compare the effects in the DAP's current state. Is it possible to bifurcate the reporting so that one profile gets their data run through the filters, and one is "raw"?

**Comment by pavgup** [comment]
@konklone that sounds like a great idea.  It's be interesting to peruse raw data.

@smarina04 that sounds like an entirely reasonable setup, but if the intent was not to point browsers at functional URLs (i.e., resolvable domain names) on analytics.usa.gov then why have links at all? I think there might be a better approach that embraces the IETF DNS standards and simultaneously keeps the data appropriately grouped:

1. If possible, post-process raw data to accommodate grouping needs or walk the less clear path <sup>[1](#RFC4343)</sup> of lowercasing all the ASCII labels to assemble some uniformity.  @konklone, I could be wrong about the case sensitivity thing here, but I'm reading the standards just a wee bit differently than you.

2. Ideally, never chop up the domain labels (e.g., label1.thelabelagency.thegovlabel). @smarina04, it's not clear what benefit you're getting from modifying the domain names themselves.  I happened across nasa.gov (and after pondering things, I think they're reading the ol' standards correctly in #171) and me thinks they deserve to be represented by the domain that they likely show up with in the data.  @konklone's whitelist approach is fair, but it's the solution that leaves a stovepipe when I think you can just skip this part of the filter. If I'm correct in the point above, you should be able to smooth out the lumps in your data due purely to case sensitivity.

Yikes, I don't mean for this to be so strict and bitter.  You both are rockstars.  These are just my $0.02 and I might be way off. 

<a name="RFC4343">1</a>:  By-in-large, ASCII characters in domain labels except when outside the ASCII character set (e.g., in :8ball: .nasa.gov the :8ball: falls outside the ASCII set and is case sensitive though normally represented by punycode).  RFC 4343 (http://gp.gg/4m), out of Motorola, tried to clarify that space in January 2006.

**Comment by konklone** [comment]
Another way of handling this would be to capture the original full URL as a custom variable during pageview reporting, so that it's associated with each hit. Then we have the admin-friendly URL, and the link-friendly URL both available to us.

That's not a fully thought through idea -- and since we generally are aggregating on sessions or users and not pageviews, it's not clear to me how we'd get the "associated" original full URL for a given page that appears in the real-time Top 20 report.

cc @laurenancona

**Comment by laurenancona** [comment]
Ah, "associated" was a reference to the method by which the custom dimension in GA: you define a scope of 'hit', 'session' or 'user' when you add it via admin panel. It's just a matter of how long you'd like that value to persist per...clientID, I guess you could say.

**Comment by laurenancona** [comment]
To elaborate: I'd mentioned this to @konklone while rolling out a fork of analytics-reporter in Philadelphia. Our implementation of a rollup account agencies is done entirely using Google Tag Manager, which makes it simple to add custom variables to the GA tag for all properties with one change to the tag. Then it's just a matter of assigning the matching index number in GA and that dimension is added to all reporting as if it were a standard dimension.

From what I understand of the DAP's implementation, this would require a change to the current tracking script—not sure how big of a headache that would be.

**Comment by tdlowden** [comment]
I think we've exhausted this discussion, and while we appreciate your thoughts, the decision to maintain the filters has been made. Thanks for your solid points, all.
