### ISSUE TITLE
Allow Universal Analytics to be served via CDN

### ISSUE THREAD

**Issue by polastre** [digital-analytics-program/gov-wide-code#3]
Google Analytics is typically served via CDN, and the website adds its tracking code and metadata as variables that the analytics script can use.

With this approach, updates to the analytics javascript can be put in the CDN, and all websites using the CDN will automatically update to the use the new scripts.  It is also easier for website administrators since no files need to be copied to the server.

By then using the CDN, the script is delivered quicker to the client browser during page load.

**Comment by konklone** [comment]
A note that we now have a soon-to-be-launched dashboard at https://analytics.usa.gov. That dashboard itself needs to report its traffic to the DAP, so https://analytics.usa.gov/dap/dap.min.js is the snippet it's using to do that. 

That snippet comes minified, gzipped, and with an accompanying source map at https://analytics.usa.gov/dap/dap.min.js.map that unmaps to the full snippet at https://analyticsusa.gov/dap/dap.js.

We're now already hosting a copy of the DAP, then, over CloudFront, exactly as we originally proposed. This copy of the DAP could become the official cloud-hosted copy of the DAP, without needing to spin up any additional infrastructure.

**Comment by konklone** [comment]
The Digital Analytics Program has finalized a new central hosting location at `dap.digitalgov.gov`. I've written a piece on how the DAP secured this new central JS location over the wire:

https://www.digitalgov.gov/2015/08/14/secure-central-hosting-for-the-digital-analytics-program/

(Short of it is, we took a mildly novel approach to HTTPS configuration to break all HTTP connections to the site rather than redirect them.)

That this repo is now in its own organization which enforces narrow access (I don't have write access yself) and strict 2FA are also security measures the DAP has put in place to help guarantee integrity of the DAP code.

@smarina04 I think the issue can be closed?
